# Generated by Django 5.0.4 on 2024-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='list_number',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
