# Generated by Django 5.0.4 on 2024-04-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_candidate_id_alter_candidate_list_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='list_number',
            field=models.IntegerField(),
        ),
    ]
